build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
labels:
  org.opencontainers.image.title: Noxli
  org.opencontainers.image.description: Baby cry detector for Home Assistant
